/* ------------------------------------------------------------------ */
/*  ICD-10 DISEASE LIBRARY                                             */
/*  Comprehensive catalog of diseases with ICD-10 codes.              */
/*  Tracked diseases are flagged and link to MV-AIHS surveillance data */
/* ------------------------------------------------------------------ */

export interface IcdDisease {
  /** Unique slug used in filter state (e.g. "dengue", "a09", "j11") */
  code: string;
  name: string;
  icd10: string;
  /** Broad clinical/administrative chapter */
  chapter: string;
  /** Fine category for search/grouping */
  category: string;
  /** True = MV-AIHS has encounter data for this disease */
  tracked: boolean;
  notifiable?: boolean;
}

/** Diseases that have real encounter data in MV-AIHS surveillance */
export const TRACKED_CODES = new Set<string>([
  "ili","dengue","gastro","febrile_seizure","chest_pain",
  "dehydration","influenza","pneumonia","diarrhea","hfmd",
]);

const ICD_DISEASES: IcdDisease[] = [
  // ── Chapter A-B  Infectious & Parasitic ────────────────────────────
  { code: "a00", name: "Cholera", icd10: "A00", chapter: "Infectious & Parasitic", category: "enteric", tracked: false, notifiable: true },
  { code: "a01", name: "Typhoid & Paratyphoid Fevers", icd10: "A01", chapter: "Infectious & Parasitic", category: "enteric", tracked: false, notifiable: true },
  { code: "a02", name: "Salmonella Infection", icd10: "A02", chapter: "Infectious & Parasitic", category: "enteric", tracked: false, notifiable: true },
  { code: "a03", name: "Shigellosis (Bacillary Dysentery)", icd10: "A03", chapter: "Infectious & Parasitic", category: "enteric", tracked: false, notifiable: true },
  { code: "a04", name: "Other Bacterial Intestinal Infections", icd10: "A04", chapter: "Infectious & Parasitic", category: "enteric", tracked: false },
  { code: "a05", name: "Foodborne Staphylococcal Intoxication", icd10: "A05", chapter: "Infectious & Parasitic", category: "enteric", tracked: false },
  { code: "diarrhea", name: "Acute Diarrhea", icd10: "A09", chapter: "Infectious & Parasitic", category: "enteric", tracked: true, notifiable: true },
  { code: "a15", name: "Tuberculosis (Respiratory)", icd10: "A15", chapter: "Infectious & Parasitic", category: "respiratory", tracked: false, notifiable: true },
  { code: "a17", name: "Tuberculosis (Nervous System)", icd10: "A17", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a20", name: "Plague", icd10: "A20", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "a21", name: "Tularemia", icd10: "A21", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "a22", name: "Anthrax", icd10: "A22", chapter: "Infectious & Parasitic", category: "other", tracked: false, notifiable: true },
  { code: "a23", name: "Brucellosis", icd10: "A23", chapter: "Infectious & Parasitic", category: "other", tracked: false, notifiable: true },
  { code: "a27", name: "Leptospirosis", icd10: "A27", chapter: "Infectious & Parasitic", category: "other", tracked: false, notifiable: true },
  { code: "a28", name: "Rat-bite Fever", icd10: "A28", chapter: "Infectious & Parasitic", category: "other", tracked: false },
  { code: "a30", name: "Leprosy", icd10: "A30", chapter: "Infectious & Parasitic", category: "dermatological", tracked: false, notifiable: true },
  { code: "a33", name: "Neonatal Tetanus", icd10: "A33", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a34", name: "Obstetrical Tetanus", icd10: "A34", chapter: "Infectious & Parasitic", category: "other", tracked: false, notifiable: true },
  { code: "a35", name: "Other Tetanus", icd10: "A35", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a36", name: "Diphtheria", icd10: "A36", chapter: "Infectious & Parasitic", category: "respiratory", tracked: false, notifiable: true },
  { code: "a37", name: "Whooping Cough (Pertussis)", icd10: "A37", chapter: "Infectious & Parasitic", category: "respiratory", tracked: false, notifiable: true },
  { code: "a38", name: "Scarlet Fever", icd10: "A38", chapter: "Infectious & Parasitic", category: "other", tracked: false },
  { code: "a39", name: "Meningococcal Meningitis", icd10: "A39", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a40", name: "Streptococcal Septicaemia", icd10: "A40", chapter: "Infectious & Parasitic", category: "other", tracked: false },
  { code: "a41", name: "Other Septicaemia / Sepsis", icd10: "A41", chapter: "Infectious & Parasitic", category: "other", tracked: false },
  { code: "a46", name: "Erysipelas", icd10: "A46", chapter: "Infectious & Parasitic", category: "dermatological", tracked: false },
  { code: "a49", name: "Bacterial Infection (Unspecified)", icd10: "A49", chapter: "Infectious & Parasitic", category: "other", tracked: false },
  { code: "a50", name: "Congenital Syphilis", icd10: "A50", chapter: "Infectious & Parasitic", category: "sexual-health", tracked: false, notifiable: true },
  { code: "a51", name: "Early Syphilis", icd10: "A51", chapter: "Infectious & Parasitic", category: "sexual-health", tracked: false, notifiable: true },
  { code: "a54", name: "Gonococcal Infection", icd10: "A54", chapter: "Infectious & Parasitic", category: "sexual-health", tracked: false, notifiable: true },
  { code: "a56", name: "Chlamydial Infection", icd10: "A56", chapter: "Infectious & Parasitic", category: "sexual-health", tracked: false },
  { code: "a59", name: "Trichomoniasis", icd10: "A59", chapter: "Infectious & Parasitic", category: "sexual-health", tracked: false },
  { code: "a60", name: "Herpes Simplex (Anogenital)", icd10: "A60", chapter: "Infectious & Parasitic", category: "sexual-health", tracked: false },
  { code: "a63", name: "Condyloma Acuminata (HPV Warts)", icd10: "A63", chapter: "Infectious & Parasitic", category: "sexual-health", tracked: false },
  { code: "a69", name: "Lyme Disease", icd10: "A69.2", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false },
  { code: "a75", name: "Typhus Fever", icd10: "A75", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "a80", name: "Acute Poliomyelitis", icd10: "A80", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a82", name: "Rabies", icd10: "A82", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a83", name: "Mosquito-borne Viral Encephalitis (JE etc.)", icd10: "A83", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a84", name: "Tick-borne Viral Encephalitis", icd10: "A84", chapter: "Infectious & Parasitic", category: "neurological", tracked: false, notifiable: true },
  { code: "a87", name: "Viral Meningitis", icd10: "A87", chapter: "Infectious & Parasitic", category: "neurological", tracked: false },
  { code: "dengue", name: "Dengue Fever", icd10: "A90", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: true, notifiable: true },
  { code: "a91", name: "Dengue Haemorrhagic Fever", icd10: "A91", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "a92", name: "Other Mosquito-borne Viral Fevers (Chikungunya)", icd10: "A92", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "a94", name: "Unspecified Arthropod-borne Viral Fever", icd10: "A94", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false },
  { code: "a95", name: "Yellow Fever", icd10: "A95", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "a96", name: "Lassa Fever / Arenaviral Haemorrhagic Fevers", icd10: "A96", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "a98", name: "Ebola / Marburg Haemorrhagic Fever", icd10: "A98", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "a99", name: "Unspecified Viral Haemorrhagic Fever", icd10: "A99", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "b00", name: "Herpes Simplex", icd10: "B00", chapter: "Infectious & Parasitic", category: "viral", tracked: false },
  { code: "b01", name: "Chickenpox (Varicella)", icd10: "B01", chapter: "Infectious & Parasitic", category: "viral", tracked: false },
  { code: "b02", name: "Herpes Zoster (Shingles)", icd10: "B02", chapter: "Infectious & Parasitic", category: "viral", tracked: false },
  { code: "b03", name: "Smallpox", icd10: "B03", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "b04", name: "Monkeypox", icd10: "B04", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "b05", name: "Measles", icd10: "B05", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "b06", name: "Rubella", icd10: "B06", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "b07", name: "Viral Warts", icd10: "B07", chapter: "Infectious & Parasitic", category: "dermatological", tracked: false },
  { code: "hfmd", name: "Hand-Foot-Mouth Disease (HFMD)", icd10: "B08.4", chapter: "Infectious & Parasitic", category: "viral", tracked: true, notifiable: true },
  { code: "b09", name: "Unspecified Viral Infection with Skin/Mucous Lesions", icd10: "B09", chapter: "Infectious & Parasitic", category: "viral", tracked: false },
  { code: "b15", name: "Acute Hepatitis A", icd10: "B15", chapter: "Infectious & Parasitic", category: "hepatic", tracked: false, notifiable: true },
  { code: "b16", name: "Acute Hepatitis B", icd10: "B16", chapter: "Infectious & Parasitic", category: "hepatic", tracked: false, notifiable: true },
  { code: "b17", name: "Acute Hepatitis C", icd10: "B17", chapter: "Infectious & Parasitic", category: "hepatic", tracked: false, notifiable: true },
  { code: "b18", name: "Chronic Viral Hepatitis", icd10: "B18", chapter: "Infectious & Parasitic", category: "hepatic", tracked: false },
  { code: "b20", name: "HIV Disease — Infectious & Parasitic Complications", icd10: "B20", chapter: "Infectious & Parasitic", category: "immunological", tracked: false, notifiable: true },
  { code: "b23", name: "HIV — Other Conditions", icd10: "B23", chapter: "Infectious & Parasitic", category: "immunological", tracked: false },
  { code: "b24", name: "HIV Disease (Unspecified)", icd10: "B24", chapter: "Infectious & Parasitic", category: "immunological", tracked: false },
  { code: "b25", name: "Cytomegalovirus Disease", icd10: "B25", chapter: "Infectious & Parasitic", category: "viral", tracked: false },
  { code: "b26", name: "Mumps", icd10: "B26", chapter: "Infectious & Parasitic", category: "viral", tracked: false, notifiable: true },
  { code: "b27", name: "Infectious Mononucleosis (EBV)", icd10: "B27", chapter: "Infectious & Parasitic", category: "viral", tracked: false },
  { code: "b34", name: "Viral Infection (Unspecified)", icd10: "B34", chapter: "Infectious & Parasitic", category: "viral", tracked: false },
  { code: "b35", name: "Dermatophytosis (Ringworm)", icd10: "B35", chapter: "Infectious & Parasitic", category: "dermatological", tracked: false },
  { code: "b37", name: "Candidiasis", icd10: "B37", chapter: "Infectious & Parasitic", category: "fungal", tracked: false },
  { code: "b38", name: "Coccidioidomycosis", icd10: "B38", chapter: "Infectious & Parasitic", category: "fungal", tracked: false },
  { code: "b40", name: "Blastomycosis", icd10: "B40", chapter: "Infectious & Parasitic", category: "fungal", tracked: false },
  { code: "b44", name: "Aspergillosis", icd10: "B44", chapter: "Infectious & Parasitic", category: "fungal", tracked: false },
  { code: "b50", name: "Malaria (P. falciparum)", icd10: "B50", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "b51", name: "Malaria (P. vivax)", icd10: "B51", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "b52", name: "Malaria (P. malariae)", icd10: "B52", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "b54", name: "Malaria (Unspecified)", icd10: "B54", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "b55", name: "Leishmaniasis", icd10: "B55", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "b56", name: "African Trypanosomiasis", icd10: "B56", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false, notifiable: true },
  { code: "b57", name: "Chagas Disease", icd10: "B57", chapter: "Infectious & Parasitic", category: "vector-borne", tracked: false },
  { code: "b65", name: "Schistosomiasis (Bilharzia)", icd10: "B65", chapter: "Infectious & Parasitic", category: "parasitic", tracked: false, notifiable: true },
  { code: "b73", name: "Onchocerciasis (River Blindness)", icd10: "B73", chapter: "Infectious & Parasitic", category: "parasitic", tracked: false },
  { code: "b74", name: "Filariasis", icd10: "B74", chapter: "Infectious & Parasitic", category: "parasitic", tracked: false },
  { code: "b76", name: "Hookworm Disease", icd10: "B76", chapter: "Infectious & Parasitic", category: "parasitic", tracked: false },
  { code: "b77", name: "Ascariasis (Roundworm)", icd10: "B77", chapter: "Infectious & Parasitic", category: "parasitic", tracked: false },
  { code: "b80", name: "Enterobiasis (Pinworm)", icd10: "B80", chapter: "Infectious & Parasitic", category: "parasitic", tracked: false },

  // ── Chapter C  Neoplasms ────────────────────────────────────────────
  { code: "c00", name: "Malignant Neoplasm of Lip", icd10: "C00", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c15", name: "Oesophageal Cancer", icd10: "C15", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c16", name: "Stomach Cancer (Gastric)", icd10: "C16", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c18", name: "Colon Cancer", icd10: "C18", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c20", name: "Rectal Cancer", icd10: "C20", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c22", name: "Hepatocellular Carcinoma (Liver Cancer)", icd10: "C22", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c25", name: "Pancreatic Cancer", icd10: "C25", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c33", name: "Tracheal Cancer", icd10: "C33", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c34", name: "Lung Cancer", icd10: "C34", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c43", name: "Melanoma of Skin", icd10: "C43", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c44", name: "Other Skin Cancer", icd10: "C44", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c50", name: "Breast Cancer", icd10: "C50", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c53", name: "Cervical Cancer", icd10: "C53", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c54", name: "Uterine (Endometrial) Cancer", icd10: "C54", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c56", name: "Ovarian Cancer", icd10: "C56", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c61", name: "Prostate Cancer", icd10: "C61", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c64", name: "Renal Cell Carcinoma (Kidney Cancer)", icd10: "C64", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c67", name: "Bladder Cancer", icd10: "C67", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c71", name: "Brain Cancer", icd10: "C71", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c73", name: "Thyroid Cancer", icd10: "C73", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c81", name: "Hodgkin Lymphoma", icd10: "C81", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c83", name: "Non-Hodgkin Lymphoma", icd10: "C83", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c90", name: "Multiple Myeloma", icd10: "C90", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c91", name: "Lymphoid Leukaemia", icd10: "C91", chapter: "Neoplasms", category: "oncology", tracked: false },
  { code: "c92", name: "Myeloid Leukaemia", icd10: "C92", chapter: "Neoplasms", category: "oncology", tracked: false },

  // ── Chapter D  Blood & Immune ───────────────────────────────────────
  { code: "d50", name: "Iron Deficiency Anaemia", icd10: "D50", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d51", name: "Vitamin B12 Deficiency Anaemia", icd10: "D51", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d52", name: "Folate Deficiency Anaemia", icd10: "D52", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d55", name: "Haemolytic Anaemia (G6PD)", icd10: "D55", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d56", name: "Thalassaemia", icd10: "D56", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d57", name: "Sickle-cell Disorders", icd10: "D57", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d64", name: "Other Anaemia", icd10: "D64", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d65", name: "Disseminated Intravascular Coagulation (DIC)", icd10: "D65", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d68", name: "Other Coagulation Defects (Haemophilia)", icd10: "D68", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d70", name: "Neutropenia", icd10: "D70", chapter: "Blood & Haematopoietic", category: "haematological", tracked: false },
  { code: "d80", name: "Immunodeficiency with Antibody Defects", icd10: "D80", chapter: "Blood & Haematopoietic", category: "immunological", tracked: false },
  { code: "d84", name: "Other Immunodeficiencies", icd10: "D84", chapter: "Blood & Haematopoietic", category: "immunological", tracked: false },

  // ── Chapter E  Endocrine & Metabolic ───────────────────────────────
  { code: "e03", name: "Hypothyroidism", icd10: "E03", chapter: "Endocrine & Metabolic", category: "endocrine", tracked: false },
  { code: "e05", name: "Hyperthyroidism (Thyrotoxicosis)", icd10: "E05", chapter: "Endocrine & Metabolic", category: "endocrine", tracked: false },
  { code: "e10", name: "Type 1 Diabetes Mellitus", icd10: "E10", chapter: "Endocrine & Metabolic", category: "metabolic", tracked: false },
  { code: "e11", name: "Type 2 Diabetes Mellitus", icd10: "E11", chapter: "Endocrine & Metabolic", category: "metabolic", tracked: false },
  { code: "e13", name: "Other Specified Diabetes Mellitus", icd10: "E13", chapter: "Endocrine & Metabolic", category: "metabolic", tracked: false },
  { code: "e14", name: "Unspecified Diabetes Mellitus", icd10: "E14", chapter: "Endocrine & Metabolic", category: "metabolic", tracked: false },
  { code: "e20", name: "Hypoparathyroidism", icd10: "E20", chapter: "Endocrine & Metabolic", category: "endocrine", tracked: false },
  { code: "e21", name: "Hyperparathyroidism", icd10: "E21", chapter: "Endocrine & Metabolic", category: "endocrine", tracked: false },
  { code: "e22", name: "Hyperpituitarism / Cushing Syndrome", icd10: "E22", chapter: "Endocrine & Metabolic", category: "endocrine", tracked: false },
  { code: "e27", name: "Adrenal Insufficiency (Addison's Disease)", icd10: "E27", chapter: "Endocrine & Metabolic", category: "endocrine", tracked: false },
  { code: "e40", name: "Kwashiorkor", icd10: "E40", chapter: "Endocrine & Metabolic", category: "nutritional", tracked: false },
  { code: "e41", name: "Marasmus / Nutritional Marasmus", icd10: "E41", chapter: "Endocrine & Metabolic", category: "nutritional", tracked: false },
  { code: "e43", name: "Severe Acute Malnutrition", icd10: "E43", chapter: "Endocrine & Metabolic", category: "nutritional", tracked: false },
  { code: "e46", name: "Unspecified Protein-Energy Malnutrition", icd10: "E46", chapter: "Endocrine & Metabolic", category: "nutritional", tracked: false },
  { code: "e50", name: "Vitamin A Deficiency", icd10: "E50", chapter: "Endocrine & Metabolic", category: "nutritional", tracked: false },
  { code: "e55", name: "Vitamin D Deficiency (Rickets)", icd10: "E55", chapter: "Endocrine & Metabolic", category: "nutritional", tracked: false },
  { code: "dehydration", name: "Severe Dehydration", icd10: "E86", chapter: "Endocrine & Metabolic", category: "metabolic", tracked: true },
  { code: "e87", name: "Other Electrolyte & Acid-Base Disturbances", icd10: "E87", chapter: "Endocrine & Metabolic", category: "metabolic", tracked: false },
  { code: "e88", name: "Other Metabolic Disorders", icd10: "E88", chapter: "Endocrine & Metabolic", category: "metabolic", tracked: false },

  // ── Chapter F  Mental & Behavioural ────────────────────────────────
  { code: "f10", name: "Alcohol Use Disorders", icd10: "F10", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f11", name: "Opioid Use Disorders", icd10: "F11", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f20", name: "Schizophrenia", icd10: "F20", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f25", name: "Schizoaffective Disorder", icd10: "F25", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f31", name: "Bipolar Affective Disorder", icd10: "F31", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f32", name: "Depressive Episode", icd10: "F32", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f33", name: "Recurrent Depressive Disorder", icd10: "F33", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f40", name: "Phobic Anxiety Disorders", icd10: "F40", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f41", name: "Generalised Anxiety Disorder (GAD)", icd10: "F41", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f43", name: "Post-Traumatic Stress Disorder (PTSD)", icd10: "F43", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f50", name: "Eating Disorders (Anorexia/Bulimia)", icd10: "F50", chapter: "Mental & Behavioural", category: "psychiatric", tracked: false },
  { code: "f70", name: "Mild Intellectual Disability", icd10: "F70", chapter: "Mental & Behavioural", category: "neurodevelopmental", tracked: false },
  { code: "f84", name: "Autism Spectrum Disorder (ASD)", icd10: "F84", chapter: "Mental & Behavioural", category: "neurodevelopmental", tracked: false },
  { code: "f90", name: "Attention-Deficit / Hyperactivity Disorder (ADHD)", icd10: "F90", chapter: "Mental & Behavioural", category: "neurodevelopmental", tracked: false },

  // ── Chapter G  Nervous System ───────────────────────────────────────
  { code: "g00", name: "Bacterial Meningitis", icd10: "G00", chapter: "Nervous System", category: "neurological", tracked: false, notifiable: true },
  { code: "g03", name: "Meningitis (Other causes)", icd10: "G03", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g04", name: "Encephalitis / Myelitis", icd10: "G04", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g20", name: "Parkinson's Disease", icd10: "G20", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g30", name: "Alzheimer's Disease", icd10: "G30", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g35", name: "Multiple Sclerosis (MS)", icd10: "G35", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g40", name: "Epilepsy", icd10: "G40", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g43", name: "Migraine", icd10: "G43", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g45", name: "Transient Cerebral Ischaemic Attack (TIA)", icd10: "G45", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g47", name: "Sleep Disorders", icd10: "G47", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g54", name: "Nerve Root & Plexus Disorders", icd10: "G54", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "g61", name: "Guillain-Barré Syndrome", icd10: "G61", chapter: "Nervous System", category: "neurological", tracked: false },
  { code: "febrile_seizure", name: "Febrile Seizure", icd10: "R56.0", chapter: "Nervous System", category: "neurological", tracked: true },

  // ── Chapter H  Eye & Ear ────────────────────────────────────────────
  { code: "h10", name: "Conjunctivitis", icd10: "H10", chapter: "Eye & Adnexa", category: "ophthalmological", tracked: false },
  { code: "h25", name: "Senile Cataract", icd10: "H25", chapter: "Eye & Adnexa", category: "ophthalmological", tracked: false },
  { code: "h35", name: "Other Retinal Disorders", icd10: "H35", chapter: "Eye & Adnexa", category: "ophthalmological", tracked: false },
  { code: "h40", name: "Glaucoma", icd10: "H40", chapter: "Eye & Adnexa", category: "ophthalmological", tracked: false },
  { code: "h54", name: "Blindness & Low Vision", icd10: "H54", chapter: "Eye & Adnexa", category: "ophthalmological", tracked: false },
  { code: "h60", name: "Otitis Externa", icd10: "H60", chapter: "Ear & Mastoid", category: "otological", tracked: false },
  { code: "h65", name: "Nonsuppurative Otitis Media", icd10: "H65", chapter: "Ear & Mastoid", category: "otological", tracked: false },
  { code: "h66", name: "Suppurative Otitis Media (Ear Infection)", icd10: "H66", chapter: "Ear & Mastoid", category: "otological", tracked: false },
  { code: "h80", name: "Otosclerosis", icd10: "H80", chapter: "Ear & Mastoid", category: "otological", tracked: false },
  { code: "h91", name: "Other Hearing Loss", icd10: "H91", chapter: "Ear & Mastoid", category: "otological", tracked: false },

  // ── Chapter I  Circulatory ──────────────────────────────────────────
  { code: "i10", name: "Essential Hypertension", icd10: "I10", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "i11", name: "Hypertensive Heart Disease", icd10: "I11", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "i20", name: "Unstable Angina", icd10: "I20", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "i21", name: "Acute Myocardial Infarction (Heart Attack)", icd10: "I21", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "i26", name: "Pulmonary Embolism", icd10: "I26", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "i48", name: "Atrial Fibrillation & Flutter", icd10: "I48", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "i50", name: "Heart Failure (Congestive)", icd10: "I50", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "chest_pain", name: "Acute Chest Pain", icd10: "R07", chapter: "Circulatory", category: "cardiac", tracked: true },
  { code: "i60", name: "Subarachnoid Haemorrhage", icd10: "I60", chapter: "Circulatory", category: "neurological", tracked: false },
  { code: "i61", name: "Intracerebral Haemorrhage (Stroke)", icd10: "I61", chapter: "Circulatory", category: "neurological", tracked: false },
  { code: "i63", name: "Cerebral Infarction (Ischaemic Stroke)", icd10: "I63", chapter: "Circulatory", category: "neurological", tracked: false },
  { code: "i70", name: "Atherosclerosis", icd10: "I70", chapter: "Circulatory", category: "cardiac", tracked: false },
  { code: "i80", name: "Deep Vein Thrombosis (DVT)", icd10: "I80", chapter: "Circulatory", category: "vascular", tracked: false },
  { code: "i83", name: "Varicose Veins of Lower Extremities", icd10: "I83", chapter: "Circulatory", category: "vascular", tracked: false },

  // ── Chapter J  Respiratory ──────────────────────────────────────────
  { code: "j00", name: "Acute Nasopharyngitis (Common Cold)", icd10: "J00", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j01", name: "Acute Sinusitis", icd10: "J01", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j02", name: "Acute Pharyngitis (Sore Throat)", icd10: "J02", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j03", name: "Acute Tonsillitis", icd10: "J03", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j06", name: "Acute Upper Respiratory Infection (URTI)", icd10: "J06", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "influenza", name: "Influenza (Confirmed)", icd10: "J10", chapter: "Respiratory", category: "respiratory", tracked: true, notifiable: true },
  { code: "ili", name: "Influenza-like Illness (ILI)", icd10: "J11", chapter: "Respiratory", category: "respiratory", tracked: true, notifiable: true },
  { code: "j12", name: "Viral Pneumonia (Non-influenza)", icd10: "J12", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j13", name: "Streptococcal Pneumonia", icd10: "J13", chapter: "Respiratory", category: "respiratory", tracked: false, notifiable: true },
  { code: "j15", name: "Bacterial Pneumonia", icd10: "J15", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "pneumonia", name: "Community-Acquired Pneumonia", icd10: "J18", chapter: "Respiratory", category: "respiratory", tracked: true, notifiable: true },
  { code: "j20", name: "Acute Bronchitis", icd10: "J20", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j21", name: "Acute Bronchiolitis", icd10: "J21", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j22", name: "Unspecified Acute Lower Respiratory Infection", icd10: "J22", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j30", name: "Allergic Rhinitis", icd10: "J30", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j32", name: "Chronic Sinusitis", icd10: "J32", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j35", name: "Chronic Tonsillitis / Adenoid Hypertrophy", icd10: "J35", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j38", name: "Vocal Cord & Larynx Disorders", icd10: "J38", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j40", name: "Bronchitis (Unspecified)", icd10: "J40", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j41", name: "Chronic Bronchitis", icd10: "J41", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j42", name: "Unspecified Chronic Bronchitis", icd10: "J42", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j43", name: "Emphysema", icd10: "J43", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j44", name: "Chronic Obstructive Pulmonary Disease (COPD)", icd10: "J44", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j45", name: "Asthma", icd10: "J45", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j46", name: "Status Asthmaticus", icd10: "J46", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j47", name: "Bronchiectasis", icd10: "J47", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j60", name: "Pneumoconiosis (Coal Workers)", icd10: "J60", chapter: "Respiratory", category: "occupational", tracked: false },
  { code: "j70", name: "Respiratory Conditions due to Other Agents", icd10: "J70", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j80", name: "Acute Respiratory Distress Syndrome (ARDS)", icd10: "J80", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j81", name: "Pulmonary Oedema", icd10: "J81", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j84", name: "Other Interstitial Lung Diseases", icd10: "J84", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j90", name: "Pleural Effusion", icd10: "J90", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j93", name: "Pneumothorax", icd10: "J93", chapter: "Respiratory", category: "respiratory", tracked: false },
  { code: "j96", name: "Respiratory Failure", icd10: "J96", chapter: "Respiratory", category: "respiratory", tracked: false },

  // ── Chapter K  Digestive ────────────────────────────────────────────
  { code: "k02", name: "Dental Caries (Tooth Decay)", icd10: "K02", chapter: "Digestive", category: "dental", tracked: false },
  { code: "k20", name: "Oesophagitis", icd10: "K20", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k21", name: "Gastro-oesophageal Reflux Disease (GORD/GERD)", icd10: "K21", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k25", name: "Gastric Ulcer", icd10: "K25", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k26", name: "Duodenal Ulcer", icd10: "K26", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k29", name: "Gastritis & Duodenitis", icd10: "K29", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k35", name: "Acute Appendicitis", icd10: "K35", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k40", name: "Inguinal Hernia", icd10: "K40", chapter: "Digestive", category: "surgical", tracked: false },
  { code: "k50", name: "Crohn's Disease", icd10: "K50", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k51", name: "Ulcerative Colitis", icd10: "K51", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "gastro", name: "Gastroenteritis", icd10: "K52", chapter: "Digestive", category: "enteric", tracked: true, notifiable: true },
  { code: "k57", name: "Diverticular Disease of Colon", icd10: "K57", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k59", name: "Other Functional Intestinal Disorders (IBS, Constipation)", icd10: "K59", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k70", name: "Alcoholic Liver Disease", icd10: "K70", chapter: "Digestive", category: "hepatic", tracked: false },
  { code: "k74", name: "Fibrosis & Cirrhosis of Liver", icd10: "K74", chapter: "Digestive", category: "hepatic", tracked: false },
  { code: "k80", name: "Cholelithiasis (Gallstones)", icd10: "K80", chapter: "Digestive", category: "hepatic", tracked: false },
  { code: "k85", name: "Acute Pancreatitis", icd10: "K85", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k86", name: "Other Diseases of Pancreas (Chronic Pancreatitis)", icd10: "K86", chapter: "Digestive", category: "enteric", tracked: false },
  { code: "k92", name: "Upper GI Bleeding / Haematemesis", icd10: "K92", chapter: "Digestive", category: "enteric", tracked: false },

  // ── Chapter L  Skin ─────────────────────────────────────────────────
  { code: "l01", name: "Impetigo", icd10: "L01", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l02", name: "Cutaneous Abscess / Furuncle", icd10: "L02", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l03", name: "Cellulitis", icd10: "L03", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l20", name: "Atopic Dermatitis (Eczema)", icd10: "L20", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l23", name: "Allergic Contact Dermatitis", icd10: "L23", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l29", name: "Pruritus (Itching)", icd10: "L29", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l40", name: "Psoriasis", icd10: "L40", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l50", name: "Urticaria (Hives)", icd10: "L50", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l53", name: "Other Erythematous Conditions", icd10: "L53", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l60", name: "Nail Disorders", icd10: "L60", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },
  { code: "l72", name: "Follicular Cysts of Skin (Sebaceous Cyst)", icd10: "L72", chapter: "Skin & Subcutaneous", category: "dermatological", tracked: false },

  // ── Chapter M  Musculoskeletal ──────────────────────────────────────
  { code: "m06", name: "Rheumatoid Arthritis", icd10: "M06", chapter: "Musculoskeletal", category: "rheumatological", tracked: false },
  { code: "m10", name: "Gout", icd10: "M10", chapter: "Musculoskeletal", category: "rheumatological", tracked: false },
  { code: "m15", name: "Polyarthritis / Osteoarthritis (Multiple)", icd10: "M15", chapter: "Musculoskeletal", category: "rheumatological", tracked: false },
  { code: "m16", name: "Hip Osteoarthritis", icd10: "M16", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m17", name: "Knee Osteoarthritis", icd10: "M17", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m32", name: "Systemic Lupus Erythematosus (SLE)", icd10: "M32", chapter: "Musculoskeletal", category: "rheumatological", tracked: false },
  { code: "m41", name: "Scoliosis", icd10: "M41", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m48", name: "Spinal Stenosis", icd10: "M48", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m50", name: "Cervical Disc Disorder", icd10: "M50", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m51", name: "Lumbar Disc Herniation", icd10: "M51", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m54", name: "Back Pain (Dorsalgia)", icd10: "M54", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m60", name: "Myositis", icd10: "M60", chapter: "Musculoskeletal", category: "rheumatological", tracked: false },
  { code: "m75", name: "Shoulder Lesions (Rotator Cuff)", icd10: "M75", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m80", name: "Osteoporosis with Fracture", icd10: "M80", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },
  { code: "m81", name: "Osteoporosis without Fracture", icd10: "M81", chapter: "Musculoskeletal", category: "orthopaedic", tracked: false },

  // ── Chapter N  Genitourinary ────────────────────────────────────────
  { code: "n00", name: "Acute Nephritic Syndrome", icd10: "N00", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n02", name: "Recurrent & Persistent Haematuria", icd10: "N02", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n03", name: "Chronic Nephritic Syndrome", icd10: "N03", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n04", name: "Nephrotic Syndrome", icd10: "N04", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n17", name: "Acute Kidney Injury (AKI)", icd10: "N17", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n18", name: "Chronic Kidney Disease (CKD)", icd10: "N18", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n20", name: "Renal Calculus (Kidney Stones)", icd10: "N20", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n30", name: "Cystitis (Bladder Infection)", icd10: "N30", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n39", name: "Urinary Tract Infection (UTI)", icd10: "N39.0", chapter: "Genitourinary", category: "renal", tracked: false },
  { code: "n40", name: "Benign Prostatic Hyperplasia (BPH)", icd10: "N40", chapter: "Genitourinary", category: "urological", tracked: false },
  { code: "n41", name: "Inflammatory Diseases of Prostate (Prostatitis)", icd10: "N41", chapter: "Genitourinary", category: "urological", tracked: false },
  { code: "n61", name: "Mastitis", icd10: "N61", chapter: "Genitourinary", category: "obstetric", tracked: false },
  { code: "n70", name: "Salpingo-oophoritis (PID)", icd10: "N70", chapter: "Genitourinary", category: "gynaecological", tracked: false },
  { code: "n76", name: "Vaginitis & Vulvitis", icd10: "N76", chapter: "Genitourinary", category: "gynaecological", tracked: false },
  { code: "n80", name: "Endometriosis", icd10: "N80", chapter: "Genitourinary", category: "gynaecological", tracked: false },
  { code: "n91", name: "Amenorrhoea / Absent Menstruation", icd10: "N91", chapter: "Genitourinary", category: "gynaecological", tracked: false },
  { code: "n92", name: "Excessive Menstrual Bleeding", icd10: "N92", chapter: "Genitourinary", category: "gynaecological", tracked: false },
  { code: "n95", name: "Menopausal Disorders", icd10: "N95", chapter: "Genitourinary", category: "gynaecological", tracked: false },

  // ── Chapter O  Obstetric ────────────────────────────────────────────
  { code: "o03", name: "Spontaneous Abortion (Miscarriage)", icd10: "O03", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o10", name: "Pre-existing Hypertension in Pregnancy", icd10: "O10", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o12", name: "Gestational Oedema & Proteinuria", icd10: "O12", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o14", name: "Pre-eclampsia", icd10: "O14", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o15", name: "Eclampsia", icd10: "O15", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false, notifiable: true },
  { code: "o20", name: "Haemorrhage in Early Pregnancy (APH)", icd10: "O20", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o24", name: "Gestational Diabetes Mellitus (GDM)", icd10: "O24", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o34", name: "Placenta Praevia", icd10: "O34.0", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o42", name: "Premature Rupture of Membranes (PROM)", icd10: "O42", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o60", name: "Preterm Labour", icd10: "O60", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o72", name: "Postpartum Haemorrhage (PPH)", icd10: "O72", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },
  { code: "o85", name: "Puerperal Sepsis", icd10: "O85", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false, notifiable: true },
  { code: "o86", name: "Other Puerperal Infections", icd10: "O86", chapter: "Pregnancy & Obstetric", category: "obstetric", tracked: false },

  // ── Chapter P  Perinatal ────────────────────────────────────────────
  { code: "p07", name: "Disorders of Low Birthweight / Prematurity", icd10: "P07", chapter: "Perinatal", category: "neonatal", tracked: false },
  { code: "p10", name: "Birth Trauma to Brain / Skull Fracture", icd10: "P10", chapter: "Perinatal", category: "neonatal", tracked: false },
  { code: "p20", name: "Foetal Hypoxia / Birth Asphyxia", icd10: "P20", chapter: "Perinatal", category: "neonatal", tracked: false },
  { code: "p22", name: "Respiratory Distress Syndrome of Newborn", icd10: "P22", chapter: "Perinatal", category: "neonatal", tracked: false },
  { code: "p35", name: "Congenital Viral Diseases (TORCH)", icd10: "P35", chapter: "Perinatal", category: "neonatal", tracked: false },
  { code: "p36", name: "Bacterial Sepsis of Newborn", icd10: "P36", chapter: "Perinatal", category: "neonatal", tracked: false },
  { code: "p55", name: "Haemolytic Disease of Newborn (HDN)", icd10: "P55", chapter: "Perinatal", category: "neonatal", tracked: false },
  { code: "p59", name: "Neonatal Jaundice", icd10: "P59", chapter: "Perinatal", category: "neonatal", tracked: false },

  // ── Chapter Q  Congenital ───────────────────────────────────────────
  { code: "q05", name: "Spina Bifida", icd10: "Q05", chapter: "Congenital Malformations", category: "congenital", tracked: false },
  { code: "q20", name: "Congenital Malformations of Cardiac Chambers", icd10: "Q20", chapter: "Congenital Malformations", category: "congenital", tracked: false },
  { code: "q21", name: "Ventricular Septal Defect (VSD)", icd10: "Q21", chapter: "Congenital Malformations", category: "congenital", tracked: false },
  { code: "q35", name: "Cleft Palate", icd10: "Q35", chapter: "Congenital Malformations", category: "congenital", tracked: false },
  { code: "q36", name: "Cleft Lip (Harelip)", icd10: "Q36", chapter: "Congenital Malformations", category: "congenital", tracked: false },
  { code: "q90", name: "Down Syndrome (Trisomy 21)", icd10: "Q90", chapter: "Congenital Malformations", category: "congenital", tracked: false },

  // ── Chapter R  Symptoms & Signs ─────────────────────────────────────
  { code: "r00", name: "Palpitations / Abnormal Heart Rate", icd10: "R00", chapter: "Symptoms & Signs", category: "cardiac", tracked: false },
  { code: "r04", name: "Haemoptysis (Coughing Up Blood)", icd10: "R04", chapter: "Symptoms & Signs", category: "respiratory", tracked: false },
  { code: "r05", name: "Cough", icd10: "R05", chapter: "Symptoms & Signs", category: "respiratory", tracked: false },
  { code: "r06", name: "Abnormalities of Breathing (Dyspnoea)", icd10: "R06", chapter: "Symptoms & Signs", category: "respiratory", tracked: false },
  { code: "r09", name: "Other Symptoms Involving Circulatory & Respiratory Systems", icd10: "R09", chapter: "Symptoms & Signs", category: "cardiac", tracked: false },
  { code: "r10", name: "Abdominal & Pelvic Pain", icd10: "R10", chapter: "Symptoms & Signs", category: "enteric", tracked: false },
  { code: "r11", name: "Nausea & Vomiting", icd10: "R11", chapter: "Symptoms & Signs", category: "enteric", tracked: false },
  { code: "r17", name: "Unspecified Jaundice", icd10: "R17", chapter: "Symptoms & Signs", category: "hepatic", tracked: false },
  { code: "r19", name: "Other Symptoms Involving Digestive System", icd10: "R19", chapter: "Symptoms & Signs", category: "enteric", tracked: false },
  { code: "r42", name: "Dizziness & Giddiness", icd10: "R42", chapter: "Symptoms & Signs", category: "neurological", tracked: false },
  { code: "r50", name: "Fever of Unknown Origin (FUO)", icd10: "R50", chapter: "Symptoms & Signs", category: "other", tracked: false },
  { code: "r51", name: "Headache", icd10: "R51", chapter: "Symptoms & Signs", category: "neurological", tracked: false },
  { code: "r52", name: "Pain (Unspecified)", icd10: "R52", chapter: "Symptoms & Signs", category: "other", tracked: false },
  { code: "r53", name: "Fatigue & Malaise", icd10: "R53", chapter: "Symptoms & Signs", category: "other", tracked: false },
  { code: "r55", name: "Syncope & Collapse", icd10: "R55", chapter: "Symptoms & Signs", category: "cardiac", tracked: false },

  // ── Chapter S/T  Injuries & Poisonings ─────────────────────────────
  { code: "s00", name: "Superficial Injury of Head", icd10: "S00", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s02", name: "Skull Fracture", icd10: "S02", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s06", name: "Traumatic Brain Injury (TBI)", icd10: "S06", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s09", name: "Other Head Injuries", icd10: "S09", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s22", name: "Rib / Sternum / Thoracic Spine Fracture", icd10: "S22", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s32", name: "Fracture of Lumbar Spine & Pelvis", icd10: "S32", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s42", name: "Fracture of Shoulder & Upper Arm", icd10: "S42", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s52", name: "Fracture of Forearm (Radius/Ulna)", icd10: "S52", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s72", name: "Fracture of Femur (Hip Fracture)", icd10: "S72", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s82", name: "Fracture of Lower Leg (Tibia/Fibula)", icd10: "S82", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "s93", name: "Ankle Sprain", icd10: "S93", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "t14", name: "Injury of Unspecified Body Region", icd10: "T14", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "t20", name: "Burns (Head & Face)", icd10: "T20", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "t30", name: "Burns (Unspecified Body Area)", icd10: "T30", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "t36", name: "Poisoning — Antibiotics", icd10: "T36", chapter: "Injury & Poisoning", category: "toxicological", tracked: false },
  { code: "t39", name: "Paracetamol Overdose", icd10: "T39.1", chapter: "Injury & Poisoning", category: "toxicological", tracked: false },
  { code: "t42", name: "Benzodiazepine Poisoning / Overdose", icd10: "T42", chapter: "Injury & Poisoning", category: "toxicological", tracked: false },
  { code: "t50", name: "Poisoning by Diuretics & Other Drugs", icd10: "T50", chapter: "Injury & Poisoning", category: "toxicological", tracked: false },
  { code: "t63", name: "Toxic Effect — Venomous Animals (Snake/Jellyfish)", icd10: "T63", chapter: "Injury & Poisoning", category: "toxicological", tracked: false },
  { code: "t70", name: "Barotrauma / Decompression Sickness (Diving)", icd10: "T70", chapter: "Injury & Poisoning", category: "other", tracked: false },
  { code: "t71", name: "Asphyxia (Near-drowning)", icd10: "T71", chapter: "Injury & Poisoning", category: "trauma", tracked: false },
  { code: "t75", name: "Effects of Extreme Heat (Heatstroke)", icd10: "T67", chapter: "Injury & Poisoning", category: "environmental", tracked: false },

  // ── Chapter U  COVID-19 (extended codes) ────────────────────────────
  { code: "u07", name: "COVID-19 (SARS-CoV-2 identified)", icd10: "U07.1", chapter: "COVID-19 & Emerging", category: "viral", tracked: false, notifiable: true },
  { code: "u08", name: "COVID-19 History (Previous Diagnosis)", icd10: "U08.9", chapter: "COVID-19 & Emerging", category: "viral", tracked: false },
  { code: "u09", name: "Post-COVID Condition (Long COVID)", icd10: "U09.9", chapter: "COVID-19 & Emerging", category: "viral", tracked: false },
  { code: "u10", name: "Multisystem Inflammatory Syndrome (MIS-C)", icd10: "U10.9", chapter: "COVID-19 & Emerging", category: "viral", tracked: false, notifiable: true },

  // ── Chapter Z  Factors Influencing Health ──────────────────────────
  { code: "z00", name: "General Medical Examination (Well Visit)", icd10: "Z00", chapter: "Health Status Factors", category: "preventive", tracked: false },
  { code: "z11", name: "Encounter for Screening for Infectious Disease", icd10: "Z11", chapter: "Health Status Factors", category: "preventive", tracked: false },
  { code: "z23", name: "Encounter for Vaccination", icd10: "Z23", chapter: "Health Status Factors", category: "preventive", tracked: false },
  { code: "z34", name: "Antenatal Care (Supervision of Normal Pregnancy)", icd10: "Z34", chapter: "Health Status Factors", category: "obstetric", tracked: false },
  { code: "z47", name: "Follow-up Care After Orthopaedic Surgery", icd10: "Z47", chapter: "Health Status Factors", category: "orthopaedic", tracked: false },
  { code: "z71", name: "Health Counselling", icd10: "Z71", chapter: "Health Status Factors", category: "preventive", tracked: false },
  { code: "z72", name: "Problems Related to Lifestyle (Obesity, Smoking)", icd10: "Z72", chapter: "Health Status Factors", category: "preventive", tracked: false },
];

export const ICD_DISEASE_LIBRARY: IcdDisease[] = ICD_DISEASES;

/** Subset exported for backward compat with surveillance analytics */
export const TRACKED_ICD_DISEASES = ICD_DISEASES.filter((d) => d.tracked);

export function searchIcdLibrary(query: string): IcdDisease[] {
  const q = query.trim().toLowerCase();
  if (!q) return ICD_DISEASE_LIBRARY;
  return ICD_DISEASE_LIBRARY.filter((d) =>
    d.name.toLowerCase().includes(q) ||
    d.icd10.toLowerCase().includes(q) ||
    d.code.toLowerCase().includes(q) ||
    d.category.toLowerCase().includes(q) ||
    d.chapter.toLowerCase().includes(q)
  );
}
